resources:
- repo: self

pool:
  vmImage: 'windows-latest'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Running tests: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ'
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: 'Publish ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*-armttk.xml'
    testRunTitle: 'FortiGate Active/Active ELB-ILB ARM TTK verification'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template test Active/Active'

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ/*.md
    include:
    - FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ/*